name: "Deploy codigofacilito"

on:
  push:
    branches: ["master"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hacemos un pull del codigo"
      - run: echo "correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
      - run: echo "Se termino el ejercicio"
